#!/usr/bin/env bash
set -Eeuo pipefail

STAGE_VERSION="rnatr_general_repeat_caller_bootstrap_v0.1.1"
PROJECT_ROOT="/mnt/intelssd/rnatr_project"
SSOT_CLI="$PROJECT_ROOT/metadata/ssot/rnatr_ssot.py"
SSOT_DB="$PROJECT_ROOT/metadata/ssot/rnatr_ssot.sqlite"
STAGE6AM_QC="$PROJECT_ROOT/qc/11_six_sample_frozen_p01_replay/ENCSR307SHM_pilot100k_mm2splice_v1/rnatr_six_sample_frozen_p01_replay_v0.1.5/six_sample_frozen_p01_replay.qc.tsv"
TARGET_EVIDENCE="$PROJECT_ROOT/results/11_periodic_calibrated/ENCSR307SHM_pilot100k_mm2splice_v1/v0.3.3/simple_periodic_evidence.calibrated.v0.3.3.tsv.gz"
CONTRACT="$PROJECT_ROOT/docs/design/RNA_TR_Scout_general_repeat_caller_contract_v0.1.0.md"
CALLER_DIR="$PROJECT_ROOT/src/rnatr_scout/general_caller"
CALLER="$CALLER_DIR/rnatr_general_repeat_caller_ref_v0.1.0.py"
BENCH="$PROJECT_ROOT/benchmarks/general_repeat_caller/v0.1.0"
SELFTEST="$BENCH/rnatr_general_repeat_caller_fixture_selftest_v0.1.0.py"
QC_DIR="$PROJECT_ROOT/qc/12_general_repeat_caller_bootstrap/v0.1.0"
QC="$QC_DIR/general_repeat_caller_bootstrap.qc.tsv"
SCRIPT_INSTALL="$PROJECT_ROOT/scripts/12a_bootstrap_general_repeat_caller_v0.1.1.sh"

for p in "$SSOT_CLI" "$SSOT_DB" "$STAGE6AM_QC" "$TARGET_EVIDENCE"; do
  [[ -s "$p" ]] || { echo "ERROR: required input missing: $p" >&2; exit 2; }
done
stage6am_status="$(awk -F '\t' '$1=="stage6am_status"{print $2}' "$STAGE6AM_QC")"
[[ "$stage6am_status" == "PASS_SIX_SAMPLE_FROZEN_P01_REPLAY_COMPLETE" ]] || {
  echo "ERROR: Stage 6AM not complete: $stage6am_status" >&2; exit 2;
}

echo "===== SSOT STRUCTURAL PREFLIGHT ====="
python - "$SSOT_CLI" <<'PYSSOTPREFLIGHT'
from pathlib import Path
import re,sys
cli=Path(sys.argv[1]); text=cli.read_text(encoding='utf-8')
m=re.search(r'(?m)^TOOL_VERSION\s*=\s*["\']([^"\']+)["\']\s*$', text)
if not m:
    raise SystemExit('ERROR: SSOT TOOL_VERSION declaration not found')
required=[
    'def add_decision(', 'def add_interpretation(', 'def add_contract(',
    'CREATE TABLE open_questions', 'CREATE TABLE limitations',
    '    current_metrics = [\n'
]
missing=[x for x in required if x not in text]
if missing:
    raise SystemExit('ERROR: SSOT structural contract missing: '+', '.join(missing))
if text.count('    current_metrics = [\n') != 1:
    raise SystemExit('ERROR: SSOT current_metrics anchor is not unique')
if '# Stage 12A general caller bootstrap v0.1.0' in text:
    raise SystemExit('ERROR: Stage 12A SSOT patch marker already present; inspect existing state before rerun')
print('SSOT_STRUCTURAL_PREFLIGHT_PASS')
print('tool_version\t'+m.group(1))
PYSSOTPREFLIGHT

for p in "$CONTRACT" "$CALLER" "$SELFTEST" "$QC" "$BENCH" "$QC_DIR"; do
  [[ ! -e "$p" ]] || { echo "ERROR: refusing overwrite: $p" >&2; exit 2; }
done
mkdir -p "$(dirname "$CONTRACT")" "$CALLER_DIR" "$BENCH" "$QC_DIR"

CLI_BAK=""
DB_BAK=""
cleanup_fail() {
  rc=$?
  echo "ERROR: Stage 12A failed; cleaning newly created Stage 12A files" >&2
  if [[ -n "$CLI_BAK" && -f "$CLI_BAK" ]]; then cp -a "$CLI_BAK" "$SSOT_CLI"; fi
  if [[ -n "$DB_BAK" && -f "$DB_BAK" ]]; then cp -a "$DB_BAK" "$SSOT_DB"; fi
  rm -f "$CONTRACT" "$CALLER"
  if [[ "$BENCH" == "$PROJECT_ROOT/benchmarks/general_repeat_caller/v0.1.0" ]]; then rm -rf "$BENCH"; fi
  if [[ "$QC_DIR" == "$PROJECT_ROOT/qc/12_general_repeat_caller_bootstrap/v0.1.0" ]]; then rm -rf "$QC_DIR"; fi
  exit "$rc"
}
trap cleanup_fail ERR

CONTRACT_PATH="$CONTRACT" CALLER_PATH="$CALLER" SELFTEST_PATH="$SELFTEST" python - <<'PYDECODE'
from pathlib import Path
import base64, os
payloads={
    Path(os.environ['CONTRACT_PATH']): 'IyBSTkEtVFItU2NvdXQgR2VuZXJhbCBSZXBlYXQgQ2FsbGVyIENvbnRyYWN0IHYwLjEuMAoKIyMgU3RhdHVzCgpGcm96ZW4gYXJjaGl0ZWN0dXJlIGNvbnRyYWN0IGZvciB0aGUgbmV4dCBpbXBsZW1lbnRhdGlvbiBwaGFzZS4gVGhlIGV4aXN0aW5nIFAwL1AxIHNpbXBsZS1wZXJpb2RpYyBwaXBlbGluZSByZW1haW5zIHRoZSBjb3JyZWN0bmVzcy9yZWdyZXNzaW9uIHJlZmVyZW5jZSBhbmQgaXMgbm90IHJlcGxhY2VkIGluLXBsYWNlLgoKIyMgRGV2ZWxvcG1lbnQgc2NvcGUgZGVjaXNpb24KClRoZSBzaXggZXF1YWxpemVkIGZldGFsLWJyYWluIDEwMGstcmVhZCBkYXRhc2V0cyBhcmUgYW4gZW5naW5lZXJpbmcgdmFsaWRhdGlvbiBwYW5lbCBvbmx5LiBUaGV5IGVzdGFibGlzaCB0aGF0IHRoZSBmcm96ZW4gcGlwZWxpbmUgY2FuIHJlcGxheSBhY3Jvc3MgbXVsdGlwbGUgc2FtcGxlcyBhbmQgcmV2ZWFsIGdyb3NzIGltcGxlbWVudGF0aW9uIGFydGlmYWN0cy4gVGhleSBhcmUgbm90IGxhcmdlIGVub3VnaCB0byBlc3RpbWF0ZSBwcmVjaXNlIGxvY3VzL21vdGlmL2xlbmd0aC9zdXBwb3J0LXNwZWNpZmljIFJOQSB0ZWNobmljYWwgZGlzdHJpYnV0aW9ucy4gUG9wdWxhdGlvbi1zY2FsZSBSTkEgY2FsaWJyYXRpb24gaXMgZGVmZXJyZWQgdW50aWwgdGhlIGNhbGxlciBpcyBzdGFibGUgYW5kIHN1ZmZpY2llbnRseSBmYXN0IHRvIHByb2Nlc3MgbWFueSBzYW1wbGVzLgoKIyMgTWVhc3VyZW1lbnQgY29udHJhY3QKCjEuICoqTG9jdXMgYXNzaWdubWVudCBhbmQgcmVwZWF0IG1lYXN1cmVtZW50IHJlbWFpbiBzZXBhcmF0ZS4qKiBTcGxpY2UtYXdhcmUgZ2Vub21pYyBhbGlnbm1lbnQgYW5kIGNhdGFsb2ctZ3VpZGVkIGZsYW5rcyBhc3NpZ24gYSByZWFkIHRvIGEgbG9jdXMuIFJlcGVhdCBsZW5ndGggaXMgbWVhc3VyZWQgZnJvbSByYXctcmVhZCBzZXF1ZW5jZSwgbm90IGZyb20gdGhlIEJBTSBDSUdBUi4KMi4gKipDYXRhbG9nIG1vdGlmcyBhcmUgcHJpb3JzLCBub3QgaW1tdXRhYmxlIHRydXRoLioqIFRoZSBjYWxsZXIgbXVzdCBldmFsdWF0ZSBtb3RpZiByb3RhdGlvbnMgYW5kIHJldmVyc2UgY29tcGxlbWVudHMsIGNvbGxhcHNlIGhhcm1vbmljL3ByaW1pdGl2ZSBlcXVpdmFsZW50cywgYW5kIGxhdGVyIGFsbG93IGRlLW5vdm8gbW90aWYgaHlwb3RoZXNlcy4KMy4gKipUaGUgcHJvamVjdGVkIGNhdGFsb2cgaW50ZXJ2YWwgaXMgYSBzb2Z0IGJvdW5kYXJ5IHByaW9yLioqIFJlcGVhdCBib3VuZGFyaWVzIGFyZSByZS1lc3RpbWF0ZWQgb24gdGhlIHJhdy1yZWFkIHdpbmRvdyBhbmQgbWF5IGV4dGVuZCBiZXlvbmQgb3IgY29udHJhY3Qgd2l0aGluIHRoZSBjYXRhbG9nIGludGVydmFsIHdoZW4gc2VxdWVuY2UgZXZpZGVuY2Ugc3VwcG9ydHMgaXQuCjQuICoqVGhlIHJlZmVyZW5jZSBzZXF1ZW5jZSBtb2RlbCBpcyBhbiBlcnJvci1hd2FyZSBjeWNsaWMgcmVwZWF0IGFsaWdubWVudC4qKiBUaGUgaW1wbGVtZW50YXRpb24gdXNlcyBhIGN5Y2xpYyBtb3RpZiBzdGF0ZSBtb2RlbCB3aXRoIG1hdGNoL3N1YnN0aXR1dGlvbiwgcmVhZCBpbnNlcnRpb24sIGFuZCBtb3RpZiBkZWxldGlvbiBwYXRocy4gUHJvZHVjdGlvbiBjb2RlIG1heSByZXBsYWNlIHRoZSBpbXBsZW1lbnRhdGlvbiwgYnV0IG11c3QgcHJlc2VydmUgdGhpcyBtZWFzdXJlbWVudCBzZW1hbnRpY3MgYW5kIHJlZ3Jlc3Npb24gb3V0cHV0Lgo1LiAqKlNQQU4gYW5kIGNlbnNvcmVkIG1vbGVjdWxlcyBoYXZlIGRpZmZlcmVudCBzaXppbmcgc2VtYW50aWNzLioqIFR3by1mbGFuayBTUEFOIG1vbGVjdWxlcyBjYW4geWllbGQgYSBib3VuZGVkIHRvdGFsIHRyYWN0IGxlbmd0aC4gTEVGVC9SSUdIVC9CT1RILWNlbnNvcmVkIG1vbGVjdWxlcyB5aWVsZCBvYnNlcnZlZCByZXBlYXQgc2VxdWVuY2UgYW5kIGxvd2VyLWJvdW5kL2ludGVydmFsIGluZm9ybWF0aW9uIG9ubHk7IHRoZXkgbXVzdCBub3QgYmUgY29lcmNlZCBpbnRvIGV4YWN0IGFsbGVsZSBsZW5ndGhzLgo2LiAqKkNvbXBvdW5kIHN0cnVjdHVyZSBpcyBleHBsaWNpdC4qKiBGaW5hbCBpbXBsZW1lbnRhdGlvbiBtdXN0IHN1cHBvcnQgbXVsdGlwbGUgcmVwZWF0IG1vdGlmcyB3aXRoaW4gb25lIHRyYWN0LCB3aXRoIGEgc3dpdGNoIHBlbmFsdHkvc2VnbWVudGF0aW9uIG1vZGVsIHJhdGhlciB0aGFuIGZvcmNpbmcgb25lIG1vdGlmIGFjcm9zcyB0aGUgd2hvbGUgdHJhY3QuCjcuICoqSW50ZXJydXB0aW9ucyBhcmUgZXhwbGljaXQuKiogSW50ZXJuYWwgbm9uLXByaW1hcnktbW90aWYgc2VxdWVuY2UgbXVzdCBiZSByZXByZXNlbnRlZCBhcyBpbnRlcnJ1cHRpb24gc2VnbWVudHMgd2hlbiB0aGUgZmxhbmtpbmcgcmVwZWF0IGV2aWRlbmNlIHN1cHBvcnRzIHRyYWN0IGNvbnRpbnVpdHk7IGl0IG11c3Qgbm90IGF1dG9tYXRpY2FsbHkgdGVybWluYXRlIHRoZSByZXBlYXQuCjguICoqVHdvIExQUyBjb25jZXB0cyBhcmUgcmV0YWluZWQuKiogYGxwc19leGFjdF9zZXF1ZW5jZV9icGAgaXMgZXhhY3Qgc2VxdWVuY2UtbGV2ZWwgdW5pbnRlcnJ1cHRlZCBwZXJpb2RpY2l0eTsgYGxwc19pbmZlcnJlZF9icGAgaXMgZXJyb3ItYXdhcmUgbW90aWYtc3RhdGUgY29udGludWl0eS4gVGhleSBtdXN0IG5vdCBiZSBzaWxlbnRseSBjb25mbGF0ZWQsIGVzcGVjaWFsbHkgZm9yIE9OVCByZWFkcy4KOS4gKipMZW5ndGgsIG1vdGlmIGNvbXBvc2l0aW9uLCBhbmQgZXZpZGVuY2UgcXVhbGl0eSByZW1haW4gbW9sZWN1bGUtbGV2ZWwgb3V0cHV0cy4qKiBMb2N1cy1sZXZlbCBzdW1tYXJpZXMgYXJlIGRlcml2ZWQgbGF0ZXIgYW5kIG11c3QgcmV0YWluIHRoZSBzaW5nbGUtcmVhZCBldmlkZW5jZS4KMTAuICoqUGF0aG9nZW5pY2l0eSBpcyBub3QgaW5mZXJyZWQgZnJvbSB0aGUgUk5BIGNhbGxlci4qKiBEaXNlYXNlIHRocmVzaG9sZHMgYW5kIEROQSBwb3B1bGF0aW9uIGRpc3RyaWJ1dGlvbnMgYXJlIGNvbnRleHQgbGF5ZXJzIG9ubHkuIFJOQSBldmlkZW5jZSBuZXZlciBpbXBsaWVzIGEgcGVyc29uYWwgRE5BIGdlbm90eXBlLgoKIyMgTW90aWYgaHlwb3RoZXNpcyBjb250cmFjdAoKVGhlIGZpbmFsIGNhbGxlciBtdXN0IGNvbnN0cnVjdCBhIG1vdGlmIGh5cG90aGVzaXMgc2V0IGZyb206CgotIGNhdGFsb2cgbW90aWYocyksIGFsbCBjeWNsaWMgcm90YXRpb25zLCBhbmQgcmV2ZXJzZS1jb21wbGVtZW50IGVxdWl2YWxlbnRzOwotIHByaW1pdGl2ZS1tb3RpZiBjb2xsYXBzZSB0byBhdm9pZCBoYXJtb25pYyBhbGlhc2VzIHN1Y2ggYXMgYENBR0NBR2AgdmVyc3VzIGBDQUdgOwotIGRlLW5vdm8gcGVyaW9kaWMgY2FuZGlkYXRlcyBmcm9tIHRoZSBwcm9qZWN0ZWQgcmF3LXJlYWQgaW50ZXJ2YWwsIGNvbmZpZ3VyYWJsZSB0byBhdCBsZWFzdCBwZXJpb2RzIDEtNTAgYnkgZGVmYXVsdCwgd2hpbGUgcmV0YWluaW5nIGNhdGFsb2cgbW90aWZzIGxvbmdlciB0aGFuIHRoYXQ7Ci0gbGF0ZXIsIHJlc2lkdWFsL3NlZ21lbnQtc3BlY2lmaWMgYWx0ZXJuYXRpdmUgbW90aWYgaHlwb3RoZXNlcyBmb3IgY29tcG91bmQgdHJhY3RzLgoKVGhlIHNlbGVjdGVkIG1vdGlmIG11c3QgYmUgcmVwb3J0ZWQgaW4gY2Fub25pY2FsIGZvcm0gdG9nZXRoZXIgd2l0aCB0aGUgb3JpZW50ZWQgbW90aWYgdXNlZCBpbiB0aGUgcmVhZC4KCiMjIEJvdW5kYXJ5IGFuZCBhbGlnbm1lbnQgY29udHJhY3QKClRoZSBjb25jZXB0dWFsIG1vZGVsIGNvbnRhaW5zIGJhY2tncm91bmQgYW5kIGN5Y2xpYyByZXBlYXQgc3RhdGVzLiBBIHByYWN0aWNhbCByZWZlcmVuY2UgaW1wbGVtZW50YXRpb24gbWF5IHVzZSBhIGxvY2FsIGN5Y2xpYyBkeW5hbWljIHByb2dyYW0sIGJ1dCB0aGUgZmluYWwgY2FsbGVyIG11c3QgcHJlc2VydmU6CgotIGxvY2FsIHN0YXJ0L2VuZCBpbmZlcmVuY2Ugb24gcmF3LXJlYWQgY29vcmRpbmF0ZXM7Ci0gc3Vic3RpdHV0aW9uIGFuZCBpbmRlbCB0b2xlcmFuY2U7Ci0gc29mdCwgbm90IGhhcmQsIHVzZSBvZiBwcm9qZWN0ZWQgY2F0YWxvZyBib3VuZGFyaWVzOwotIGZsYW5rIGdlb21ldHJ5IGFzIGFuIGluZGVwZW5kZW50IGNvbmZpZGVuY2UgbGF5ZXI7Ci0gYWx0ZXJuYXRpdmUtbW90aWYgc2NvcmUgY29tcGFyaXNvbjsKLSBkZXRlcm1pbmlzdGljIHRpZS1icmVha2luZyBhbmQgcmVwcm9kdWNpYmxlIG91dHB1dC4KCiMjIFJlcXVpcmVkIG1vbGVjdWxlLWxldmVsIG91dHB1dHMKCkF0IG1pbmltdW06CgotIGxvY3VzL3JlYWQvcHJvamVjdGlvbiBpZGVudGlmaWVyczsKLSBldmlkZW5jZSBnZW9tZXRyeSBhbmQgY2Vuc29yaW5nIHN0YXRlOwotIGNhbm9uaWNhbCBtb3RpZiBhbmQgb3JpZW50ZWQgbW90aWY7Ci0gbW90aWYgc291cmNlIChgQ0FUQUxPR2AsIGBERU5PVk9gLCBsYXRlciBgQ09NUE9VTkRfU0VHTUVOVGApOwotIHJhdy1yZWFkIHRyYWN0IHN0YXJ0L2VuZCB3aGVuIGJvdW5kZWQ7Ci0gb2JzZXJ2ZWQgdHJhY3QgYnA7Ci0gZXhhY3QgbGVuZ3RoIG9yIGxvd2VyIGJvdW5kL2ludGVydmFsIHNlbWFudGljczsKLSBtb3RpZi1wYXRoIHVuaXRzOwotIG1hdGNoZXMvbWlzbWF0Y2hlcy9pbnNlcnRpb25zL2RlbGV0aW9uczsKLSBhbGlnbm1lbnQgc2NvcmUsIG5vcm1hbGl6ZWQgc2NvcmUsIHB1cml0eS9lcnJvciBmcmFjdGlvbjsKLSBpbnRlcnJ1cHRpb24gc2VnbWVudHM7Ci0gY29tcG91bmQgbW90aWYgc2VnbWVudHM7Ci0gYGxwc19leGFjdF9zZXF1ZW5jZV9icGAgYW5kIGBscHNfaW5mZXJyZWRfYnBgIHdoZW4gaW1wbGVtZW50ZWQ7Ci0gc2Vjb25kLWJlc3QvYWx0ZXJuYXRpdmUgc2NvcmUgaW5mb3JtYXRpb247Ci0gbG9jdXMtYXNzaWdubWVudCBjb25maWRlbmNlIGtlcHQgc2VwYXJhdGUgZnJvbSByZXBlYXQtbWVhc3VyZW1lbnQgY29uZmlkZW5jZS4KCiMjIEltcGxlbWVudGF0aW9uIHNlcXVlbmNlCgojIyMgUmVmZXJlbmNlIHYwLjEuMCDigJQgbm93CgotIHNpbmdsZS1tb3RpZiBjeWNsaWMgZXJyb3ItYXdhcmUgcmF3LXJlYWQgYWxpZ25tZW50OwotIGNhdGFsb2cgcHJpb3IgcGx1cyBwcmVsaW1pbmFyeSBkZS1ub3ZvIGh5cG90aGVzZXM7Ci0gcHJpbWl0aXZlL3JvdGF0aW9uL3JldmVyc2UtY29tcGxlbWVudCBub3JtYWxpemF0aW9uOwotIHJhdy1yZWFkIGJvdW5kYXJ5IHJlLWVzdGltYXRpb247Ci0gc3ludGhldGljIGZpeHR1cmVzIGFuZCBkZXRlcm1pbmlzdGljIHNlbGYtdGVzdC4KCiMjIyBOZXh0CgoxLiBjb21wb3VuZC9pbnRlcnJ1cHRpb24gc2VnbWVudGF0aW9uOwoyLiBleGFjdC1zZXF1ZW5jZSBhbmQgZXJyb3ItYXdhcmUgTFBTOwozLiBzdHJvbmdlciBkZS1ub3ZvIG1vdGlmIHJlc2N1ZSBhbmQgaGFybW9uaWMgc3VwcHJlc3Npb247CjQuIGNlbnNvcmVkLW1vbGVjdWxlIGludGVydmFsL2xvd2VyLWJvdW5kIGltcGxlbWVudGF0aW9uOwo1LiByZWFsIFAwL1AxIHJlZ3Jlc3Npb24gZml4dHVyZSBtYXRlcmlhbGl6YXRpb24gYW5kIGNvbXBhcmlzb24gYWdhaW5zdCB0aGUgZnJvemVuIGNhbGxlcjsKNi4gZGlzZWFzZS1sb2N1cyBhbmQgc2ltdWxhdGlvbiBiZW5jaG1hcms7CjcuIG9ubHkgYWZ0ZXIgY2FsbGVyIHNlbWFudGljcyBzdGFiaWxpemU6IHByb2ZpbGluZy9vcHRpbWl6YXRpb24gb2YgdGhlIGhlYXZ5IDExZi8xMWgtc3R5bGUgY29tcHV0YXRpb24sIGluY2x1ZGluZyBjb21waWxlZCBDUFUgYW5kIEdQVSBzdWl0YWJpbGl0eTsKOC4gb25seSBhZnRlciB0aGUgY2FsbGVyIGlzIHN0YWJsZSBhbmQgZmFzdDogbGFyZ2UtY29ob3J0IFJOQSB0ZWNobmljYWwvcG9wdWxhdGlvbiBjYWxpYnJhdGlvbi4KCiMjIEFjY2VwdGFuY2UgcHJpbmNpcGxlCgpBIGZhc3RlciBvciBtb3JlIHNvcGhpc3RpY2F0ZWQgaW1wbGVtZW50YXRpb24gaXMgYWNjZXB0ZWQgb25seSBpZiBpdCByZXByb2R1Y2VzIHRoZSBmcm96ZW4gcmVmZXJlbmNlIHNlbWFudGljcyBvbiByZWdyZXNzaW9uIGZpeHR1cmVzIG9yIGlmIGEgZGVsaWJlcmF0ZSBjb250cmFjdCBjaGFuZ2UgaXMgZG9jdW1lbnRlZC4gUGVyZm9ybWFuY2Ugb3B0aW1pemF0aW9uIG11c3Qgbm90IHNpbGVudGx5IGNoYW5nZSBiaW9sb2dpY2FsIGNhbGwgbWVhbmluZy4K',
    Path(os.environ['CALLER_PATH']): 'IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwpmcm9tIF9fZnV0dXJlX18gaW1wb3J0IGFubm90YXRpb25zCmltcG9ydCBhcmdwYXJzZSwgY3N2LCBqc29uLCBtYXRoCmZyb20gZGF0YWNsYXNzZXMgaW1wb3J0IGRhdGFjbGFzcywgYXNkaWN0CmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAoKRE5BPSdBQ0dUJwpDT01QPXN0ci5tYWtldHJhbnMoJ0FDR1ROJywnVEdDQU4nKQoKZGVmIHJldmNvbXAoczpzdHIpLT5zdHI6CiAgICByZXR1cm4gcy51cHBlcigpLnRyYW5zbGF0ZShDT01QKVs6Oi0xXQoKZGVmIHJvdGF0aW9ucyhzOnN0cik6CiAgICBzPXMudXBwZXIoKQogICAgcmV0dXJuIFtzW2k6XStzWzppXSBmb3IgaSBpbiByYW5nZShsZW4ocykpXQoKZGVmIHByaW1pdGl2ZV9tb3RpZihzOnN0ciktPnN0cjoKICAgIHM9cy51cHBlcigpCiAgICBpZiBub3QgcyBvciBhbnkoYyBub3QgaW4gRE5BIGZvciBjIGluIHMpOgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoZidpbnZhbGlkIG1vdGlmOiB7cyFyfScpCiAgICBmb3IgcCBpbiByYW5nZSgxLGxlbihzKSsxKToKICAgICAgICBpZiBsZW4ocyklcD09MCBhbmQgcz09c1s6cF0qKGxlbihzKS8vcCk6CiAgICAgICAgICAgIHJldHVybiBzWzpwXQogICAgcmV0dXJuIHMKCmRlZiBjYW5vbmljYWxfbW90aWYoczpzdHIpLT5zdHI6CiAgICBwPXByaW1pdGl2ZV9tb3RpZihzKQogICAgcmV0dXJuIG1pbihyb3RhdGlvbnMocCkrcm90YXRpb25zKHJldmNvbXAocCkpKQoKQGRhdGFjbGFzcwpjbGFzcyBBbGlnbm1lbnQ6CiAgICBzY29yZTogZmxvYXQKICAgIHJlYWRfc3RhcnQ6IGludAogICAgcmVhZF9lbmQ6IGludAogICAgYWxpZ25lZF9yZWFkX2JwOiBpbnQKICAgIG1vdGlmX3BhdGhfYnA6IGludAogICAgbWF0Y2hlczogaW50CiAgICBtaXNtYXRjaGVzOiBpbnQKICAgIGluc2VydGlvbnM6IGludAogICAgZGVsZXRpb25zOiBpbnQKICAgIHB1cml0eTogZmxvYXQKICAgIHBoYXNlX3N0YXJ0OiBpbnQKICAgIHBoYXNlX2VuZDogaW50CiAgICBvcmllbnRlZF9tb3RpZjogc3RyCiAgICBvcHM6IHN0cgoKQGRhdGFjbGFzcwpjbGFzcyBDYWxsOgogICAgY2FsbGVyX3ZlcnNpb246IHN0cgogICAgY2FsbF9zdGF0dXM6IHN0cgogICAgY2Fub25pY2FsX21vdGlmOiBzdHIKICAgIG9yaWVudGVkX21vdGlmOiBzdHIKICAgIG1vdGlmX3NvdXJjZTogc3RyCiAgICByZWFkX3N0YXJ0OiBpbnQKICAgIHJlYWRfZW5kOiBpbnQKICAgIHJlcGVhdF9icF9vYnNlcnZlZDogaW50CiAgICBtb3RpZl9wYXRoX2JwOiBpbnQKICAgIHJlcGVhdF91bml0c19wYXRoOiBmbG9hdAogICAgc2NvcmU6IGZsb2F0CiAgICBzY29yZV9wZXJfcmVhZF9icDogZmxvYXQKICAgIG1hdGNoZXM6IGludAogICAgbWlzbWF0Y2hlczogaW50CiAgICBpbnNlcnRpb25zOiBpbnQKICAgIGRlbGV0aW9uczogaW50CiAgICBwdXJpdHk6IGZsb2F0CiAgICBwcmlvcl9zdGFydDogaW50CiAgICBwcmlvcl9lbmQ6IGludAogICAgcHJpb3Jfc3Bhbl9icDogaW50CiAgICBsZWZ0X2V4dGVuc2lvbl9icDogaW50CiAgICByaWdodF9leHRlbnNpb25fYnA6IGludAogICAgY2F0YWxvZ19tb3RpZl91c2VkOiBib29sCiAgICBscHNfc3RhdHVzOiBzdHIKICAgIGNvbXBvdW5kX3N0YXR1czogc3RyCiAgICBub3RlOiBzdHIKCkNBTExFUl9WRVJTSU9OPSdybmF0cl9nZW5lcmFsX3JlcGVhdF9jYWxsZXJfcmVmX3YwLjEuMCcKCmRlZiBjeWNsaWNfbG9jYWxfYWxpZ24oc2VxOnN0cixtb3RpZjpzdHIsbWF0Y2g6ZmxvYXQ9Mi4wLG1pc21hdGNoOmZsb2F0PS0zLjAsCiAgICAgICAgICAgICAgICAgICAgICAgaW5zOmZsb2F0PS0zLjAsZGVsZTpmbG9hdD0tMy4wLG1heF9kZWw6aW50PTIpLT5BbGlnbm1lbnQ6CiAgICBzZXE9c2VxLnVwcGVyKCk7IG1vdGlmPW1vdGlmLnVwcGVyKCkKICAgIGlmIG5vdCBzZXEgb3Igbm90IG1vdGlmOgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoJ3NlcXVlbmNlIGFuZCBtb3RpZiBtdXN0IGJlIG5vbi1lbXB0eScpCiAgICBuLHA9bGVuKHNlcSksbGVuKG1vdGlmKQogICAgbmVnPS0xZTEwMAogICAgcHJldl9tPVtuZWddKnA7IHByZXZfaT1bbmVnXSpwCiAgICB0Yl9tPVtbTm9uZV0qcCBmb3IgXyBpbiByYW5nZShuKV0KICAgIHRiX2k9W1tOb25lXSpwIGZvciBfIGluIHJhbmdlKG4pXQogICAgYmVzdD0oMC4wLE5vbmUsTm9uZSxOb25lKQogICAgZm9yIGksYiBpbiBlbnVtZXJhdGUoc2VxKToKICAgICAgICBjdXJfbT1bbmVnXSpwOyBjdXJfaT1bbmVnXSpwCiAgICAgICAgZm9yIGogaW4gcmFuZ2UocCk6CiAgICAgICAgICAgIGVtaXQ9bWF0Y2ggaWYgYj09bW90aWZbal0gZWxzZSBtaXNtYXRjaAogICAgICAgICAgICBiZXN0X209ZW1pdDsgcHJlZD1Ob25lCiAgICAgICAgICAgIHBqPShqLTEpJXAKICAgICAgICAgICAgZm9yIHN0LGFyciBpbiAoKCdNJyxwcmV2X20pLCgnSScscHJldl9pKSk6CiAgICAgICAgICAgICAgICBzYz1hcnJbcGpdK2VtaXQKICAgICAgICAgICAgICAgIGlmIHNjPmJlc3RfbToKICAgICAgICAgICAgICAgICAgICBiZXN0X209c2M7IHByZWQ9KHN0LHBqLDApCiAgICAgICAgICAgIGZvciBkIGluIHJhbmdlKDEsbWF4X2RlbCsxKToKICAgICAgICAgICAgICAgIHBqPShqLWQtMSklcAogICAgICAgICAgICAgICAgZm9yIHN0LGFyciBpbiAoKCdNJyxwcmV2X20pLCgnSScscHJldl9pKSk6CiAgICAgICAgICAgICAgICAgICAgc2M9YXJyW3BqXStkZWxlKmQrZW1pdAogICAgICAgICAgICAgICAgICAgIGlmIHNjPmJlc3RfbToKICAgICAgICAgICAgICAgICAgICAgICAgYmVzdF9tPXNjOyBwcmVkPShzdCxwaixkKQogICAgICAgICAgICBpZiBiZXN0X20+MDoKICAgICAgICAgICAgICAgIGN1cl9tW2pdPWJlc3RfbTsgdGJfbVtpXVtqXT1wcmVkCiAgICAgICAgICAgICAgICBpZiBiZXN0X20+YmVzdFswXTogYmVzdD0oYmVzdF9tLGksJ00nLGopCiAgICAgICAgICAgIGNhbmRfbT1wcmV2X21bal0raW5zOyBjYW5kX2k9cHJldl9pW2pdK2lucwogICAgICAgICAgICBpZiBjYW5kX20+MCBvciBjYW5kX2k+MDoKICAgICAgICAgICAgICAgIGlmIGNhbmRfbT49Y2FuZF9pOgogICAgICAgICAgICAgICAgICAgIGN1cl9pW2pdPWNhbmRfbTsgdGJfaVtpXVtqXT0oJ00nLGosMCkKICAgICAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICAgICAgY3VyX2lbal09Y2FuZF9pOyB0Yl9pW2ldW2pdPSgnSScsaiwwKQogICAgICAgICAgICAgICAgaWYgY3VyX2lbal0+YmVzdFswXTogYmVzdD0oY3VyX2lbal0saSwnSScsaikKICAgICAgICBwcmV2X20scHJldl9pPWN1cl9tLGN1cl9pCiAgICBpZiBiZXN0WzFdIGlzIE5vbmU6CiAgICAgICAgcmV0dXJuIEFsaWdubWVudCgwLjAsMCwwLDAsMCwwLDAsMCwwLDAuMCwwLDAsbW90aWYsJycpCiAgICBzY29yZSxpLHN0YXRlLGo9YmVzdAogICAgZW5kPWkrMTsgcGhhc2VfZW5kPWoKICAgIG1hdGNoZXM9bWlzbWF0Y2hlcz1pbnNlcnRpb25zPWRlbGV0aW9ucz0wOyBvcHM9W10KICAgIHdoaWxlIGk+PTA6CiAgICAgICAgaWYgc3RhdGU9PSdNJzoKICAgICAgICAgICAgaWYgc2VxW2ldPT1tb3RpZltqXTogbWF0Y2hlcys9MTsgb3BzLmFwcGVuZCgnPScpCiAgICAgICAgICAgIGVsc2U6IG1pc21hdGNoZXMrPTE7IG9wcy5hcHBlbmQoJ1gnKQogICAgICAgICAgICBwcmVkPXRiX21baV1bal0KICAgICAgICAgICAgaWYgcHJlZCBpcyBOb25lOgogICAgICAgICAgICAgICAgc3RhcnQ9aTsgcGhhc2Vfc3RhcnQ9ajsgYnJlYWsKICAgICAgICAgICAgcHN0LHBqLGQ9cHJlZAogICAgICAgICAgICBpZiBkOgogICAgICAgICAgICAgICAgZGVsZXRpb25zKz1kOyBvcHMuZXh0ZW5kKCdEJypkKQogICAgICAgICAgICBpLT0xOyBzdGF0ZT1wc3Q7IGo9cGoKICAgICAgICBlbHNlOgogICAgICAgICAgICBpbnNlcnRpb25zKz0xOyBvcHMuYXBwZW5kKCdJJykKICAgICAgICAgICAgcHJlZD10Yl9pW2ldW2pdCiAgICAgICAgICAgIGlmIHByZWQgaXMgTm9uZToKICAgICAgICAgICAgICAgIHN0YXJ0PWk7IHBoYXNlX3N0YXJ0PWo7IGJyZWFrCiAgICAgICAgICAgIHBzdCxwaixfPXByZWQKICAgICAgICAgICAgaS09MTsgc3RhdGU9cHN0OyBqPXBqCiAgICBhbGlnbmVkPWVuZC1zdGFydAogICAgbW90aWZfcGF0aD1tYXRjaGVzK21pc21hdGNoZXMrZGVsZXRpb25zCiAgICBkZW5vbT1tYXRjaGVzK21pc21hdGNoZXMraW5zZXJ0aW9ucytkZWxldGlvbnMKICAgIHB1cml0eT1tYXRjaGVzL2Rlbm9tIGlmIGRlbm9tIGVsc2UgMC4wCiAgICByZXR1cm4gQWxpZ25tZW50KHNjb3JlLHN0YXJ0LGVuZCxhbGlnbmVkLG1vdGlmX3BhdGgsbWF0Y2hlcyxtaXNtYXRjaGVzLGluc2VydGlvbnMsZGVsZXRpb25zLAogICAgICAgICAgICAgICAgICAgICBwdXJpdHkscGhhc2Vfc3RhcnQscGhhc2VfZW5kLG1vdGlmLCcnLmpvaW4ocmV2ZXJzZWQob3BzKSkpCgpkZWYgY29uc2Vuc3VzX21vdGlmKHNlZ21lbnQ6c3RyLHA6aW50KToKICAgIGlmIHA8MSBvciBsZW4oc2VnbWVudCk8MypwOiByZXR1cm4gTm9uZSwwLjAKICAgIG1vdGlmPVtdOyBhZ3JlZT0wOyB0b3RhbD0wCiAgICBmb3IgaiBpbiByYW5nZShwKToKICAgICAgICBjb3VudHM9e2I6MCBmb3IgYiBpbiBETkF9CiAgICAgICAgZm9yIGkgaW4gcmFuZ2UoaixsZW4oc2VnbWVudCkscCk6CiAgICAgICAgICAgIGI9c2VnbWVudFtpXQogICAgICAgICAgICBpZiBiIGluIGNvdW50czogY291bnRzW2JdKz0xCiAgICAgICAgYj1tYXgoY291bnRzLGtleT1jb3VudHMuZ2V0KQogICAgICAgIG1vdGlmLmFwcGVuZChiKTsgYWdyZWUrPWNvdW50c1tiXTsgdG90YWwrPXN1bShjb3VudHMudmFsdWVzKCkpCiAgICByZXR1cm4gJycuam9pbihtb3RpZiksIChhZ3JlZS90b3RhbCBpZiB0b3RhbCBlbHNlIDAuMCkKCmRlZiBnZW5lcmF0ZV9oeXBvdGhlc2VzKHNlcTpzdHIscHJpb3Jfc3RhcnQ6aW50LHByaW9yX2VuZDppbnQsY2F0YWxvZ19tb3RpZnMsCiAgICAgICAgICAgICAgICAgICAgICAgIG1heF9kZW5vdm9fcGVyaW9kOmludD0yMCx0b3BfazppbnQ9Nik6CiAgICBoeXBzPXt9CiAgICBmb3IgcmF3IGluIGNhdGFsb2dfbW90aWZzIG9yIFtdOgogICAgICAgIGlmIG5vdCByYXc6IGNvbnRpbnVlCiAgICAgICAgYz1jYW5vbmljYWxfbW90aWYocmF3KQogICAgICAgIGh5cHNbY109eydzb3VyY2UnOidDQVRBTE9HJywnYWdyZWVtZW50JzoxLjAsJ3NlZWQnOnJhd30KICAgIGxvPW1heCgwLHByaW9yX3N0YXJ0KTsgaGk9bWluKGxlbihzZXEpLHByaW9yX2VuZCkKICAgIHNlZ21lbnQ9c2VxW2xvOmhpXS51cHBlcigpCiAgICBjYW5kcz1bXQogICAgbWF4cD1taW4obWF4X2Rlbm92b19wZXJpb2QsbWF4KDEsbGVuKHNlZ21lbnQpLy8zKSkKICAgIGZvciBwIGluIHJhbmdlKDEsbWF4cCsxKToKICAgICAgICBtLGE9Y29uc2Vuc3VzX21vdGlmKHNlZ21lbnQscCkKICAgICAgICBpZiBub3QgbTogY29udGludWUKICAgICAgICBjPWNhbm9uaWNhbF9tb3RpZihtKQogICAgICAgIGNhbmRzLmFwcGVuZCgoYS0wLjAwNSpsZW4oYyksYSxjLG0pKQogICAgY2FuZHMuc29ydChyZXZlcnNlPVRydWUpCiAgICBkZW5vdm9fbj0wCiAgICBmb3IgXyxhLGMsbSBpbiBjYW5kczoKICAgICAgICBpZiBjIGluIGh5cHM6IGNvbnRpbnVlCiAgICAgICAgaHlwc1tjXT17J3NvdXJjZSc6J0RFTk9WTycsJ2FncmVlbWVudCc6YSwnc2VlZCc6bX0KICAgICAgICBkZW5vdm9fbis9MQogICAgICAgIGlmIGRlbm92b19uPj10b3BfazogYnJlYWsKICAgIHJldHVybiBoeXBzCgpkZWYgY2FsbF9yZXBlYXQoc2VxOnN0cixwcmlvcl9zdGFydDppbnQscHJpb3JfZW5kOmludCxjYXRhbG9nX21vdGlmcz1Ob25lLAogICAgICAgICAgICAgICAgbWF4X2Rlbm92b19wZXJpb2Q6aW50PTIwLHRvcF9rOmludD02KS0+Q2FsbDoKICAgIHNlcT1zZXEudXBwZXIoKQogICAgaWYgcHJpb3Jfc3RhcnQ8MCBvciBwcmlvcl9lbmQ+bGVuKHNlcSkgb3IgcHJpb3JfZW5kPD1wcmlvcl9zdGFydDoKICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCdpbnZhbGlkIHByaW9yIGludGVydmFsJykKICAgIGh5cHM9Z2VuZXJhdGVfaHlwb3RoZXNlcyhzZXEscHJpb3Jfc3RhcnQscHJpb3JfZW5kLGNhdGFsb2dfbW90aWZzLG1heF9kZW5vdm9fcGVyaW9kLHRvcF9rKQogICAgaWYgbm90IGh5cHM6CiAgICAgICAgcmFpc2UgVmFsdWVFcnJvcignbm8gbW90aWYgaHlwb3RoZXNlcycpCiAgICBjYXRhbG9nX2Nhbm9ucz17Y2Fub25pY2FsX21vdGlmKHgpIGZvciB4IGluIChjYXRhbG9nX21vdGlmcyBvciBbXSkgaWYgeH0KICAgIHJhbmtlZD1bXQogICAgZm9yIGNhbm9uLG1ldGEgaW4gaHlwcy5pdGVtcygpOgogICAgICAgIGJlc3Q9Tm9uZQogICAgICAgIGZvciBvcmllbnRlZCBpbiB7Y2Fub24scmV2Y29tcChjYW5vbil9OgogICAgICAgICAgICBhbG49Y3ljbGljX2xvY2FsX2FsaWduKHNlcSxvcmllbnRlZCkKICAgICAgICAgICAgaWYgYmVzdCBpcyBOb25lIG9yIGFsbi5zY29yZT5iZXN0LnNjb3JlOiBiZXN0PWFsbgogICAgICAgIHVuaXRzPWJlc3QubW90aWZfcGF0aF9icC9tYXgoMSxsZW4oY2Fub24pKQogICAgICAgIG9iamVjdGl2ZT1iZXN0LnNjb3JlLTEuNSpsZW4oY2Fub24pKyg4LjAgaWYgY2Fub24gaW4gY2F0YWxvZ19jYW5vbnMgZWxzZSAwLjApCiAgICAgICAgaWYgdW5pdHM8Mzogb2JqZWN0aXZlLT0yMC4wCiAgICAgICAgcmFua2VkLmFwcGVuZCgob2JqZWN0aXZlLGNhbm9uLG1ldGEsYmVzdCkpCiAgICByYW5rZWQuc29ydChrZXk9bGFtYmRhIHg6KHhbMF0seFszXS5zY29yZSwtbGVuKHhbMV0pKSxyZXZlcnNlPVRydWUpCiAgICBvYmplY3RpdmUsY2Fub24sbWV0YSxiZXN0PXJhbmtlZFswXQogICAgc3RhdHVzPSdQQVNTJyBpZiBiZXN0LmFsaWduZWRfcmVhZF9icD49MypsZW4oY2Fub24pIGFuZCBiZXN0LnB1cml0eT49MC41NSBlbHNlICdMT1dfQ09ORklERU5DRScKICAgIHJldHVybiBDYWxsKAogICAgICAgIENBTExFUl9WRVJTSU9OLHN0YXR1cyxjYW5vbixiZXN0Lm9yaWVudGVkX21vdGlmLG1ldGFbJ3NvdXJjZSddLGJlc3QucmVhZF9zdGFydCxiZXN0LnJlYWRfZW5kLAogICAgICAgIGJlc3QuYWxpZ25lZF9yZWFkX2JwLGJlc3QubW90aWZfcGF0aF9icCxiZXN0Lm1vdGlmX3BhdGhfYnAvbGVuKGNhbm9uKSxiZXN0LnNjb3JlLAogICAgICAgIGJlc3Quc2NvcmUvbWF4KDEsYmVzdC5hbGlnbmVkX3JlYWRfYnApLGJlc3QubWF0Y2hlcyxiZXN0Lm1pc21hdGNoZXMsYmVzdC5pbnNlcnRpb25zLGJlc3QuZGVsZXRpb25zLAogICAgICAgIGJlc3QucHVyaXR5LHByaW9yX3N0YXJ0LHByaW9yX2VuZCxwcmlvcl9lbmQtcHJpb3Jfc3RhcnQscHJpb3Jfc3RhcnQtYmVzdC5yZWFkX3N0YXJ0LAogICAgICAgIGJlc3QucmVhZF9lbmQtcHJpb3JfZW5kLGNhbm9uIGluIGNhdGFsb2dfY2Fub25zLAogICAgICAgICdOT1RfSU1QTEVNRU5URURfSU5fUkVGX1YwLjEuMCcsJ05PVF9JTVBMRU1FTlRFRF9JTl9SRUZfVjAuMS4wJywKICAgICAgICAnUmVmZXJlbmNlIHNpbmdsZS1tb3RpZiBjb3JlIG9ubHk7IGNvbXBvdW5kIHNlZ21lbnRhdGlvbiwgaW50ZXJydXB0aW9uLWF3YXJlIExQUywgY2Vuc29yZWQgaW5mZXJlbmNlLCBhbmQgcHJvZHVjdGlvbiBvcHRpbWl6YXRpb24gYXJlIGxhdGVyIHN0YWdlcy4nCiAgICApCgpkZWYgY2xpKCk6CiAgICBhcD1hcmdwYXJzZS5Bcmd1bWVudFBhcnNlcigpCiAgICBhcC5hZGRfYXJndW1lbnQoJy0tc2VxdWVuY2UnKQogICAgYXAuYWRkX2FyZ3VtZW50KCctLWlucHV0LXRzdicsdHlwZT1QYXRoKQogICAgYXAuYWRkX2FyZ3VtZW50KCctLW91dHB1dC10c3YnLHR5cGU9UGF0aCkKICAgIGFwLmFkZF9hcmd1bWVudCgnLS1wcmlvci1zdGFydCcsdHlwZT1pbnQpCiAgICBhcC5hZGRfYXJndW1lbnQoJy0tcHJpb3ItZW5kJyx0eXBlPWludCkKICAgIGFwLmFkZF9hcmd1bWVudCgnLS1jYXRhbG9nLW1vdGlmJyxhY3Rpb249J2FwcGVuZCcsZGVmYXVsdD1bXSkKICAgIGFyZ3M9YXAucGFyc2VfYXJncygpCiAgICBpZiBhcmdzLmlucHV0X3RzdjoKICAgICAgICBpZiBub3QgYXJncy5vdXRwdXRfdHN2OiBhcC5lcnJvcignLS1vdXRwdXQtdHN2IGlzIHJlcXVpcmVkIHdpdGggLS1pbnB1dC10c3YnKQogICAgICAgIHJvd3M9W10KICAgICAgICB3aXRoIGFyZ3MuaW5wdXRfdHN2Lm9wZW4oKSBhcyBmaDoKICAgICAgICAgICAgcmQ9Y3N2LkRpY3RSZWFkZXIoZmgsZGVsaW1pdGVyPSdcdCcpCiAgICAgICAgICAgIGZvciByb3cgaW4gcmQ6CiAgICAgICAgICAgICAgICBtb3RpZnM9W3ggZm9yIHggaW4gcm93LmdldCgnY2F0YWxvZ19tb3RpZicsJycpLnNwbGl0KCcsJykgaWYgeF0KICAgICAgICAgICAgICAgIGNhbGw9Y2FsbF9yZXBlYXQocm93WydzZXF1ZW5jZSddLGludChyb3dbJ3ByaW9yX3N0YXJ0J10pLGludChyb3dbJ3ByaW9yX2VuZCddKSxtb3RpZnMpCiAgICAgICAgICAgICAgICBvdXQ9eydjYXNlX2lkJzpyb3cuZ2V0KCdjYXNlX2lkJywnJyksKiphc2RpY3QoY2FsbCl9CiAgICAgICAgICAgICAgICByb3dzLmFwcGVuZChvdXQpCiAgICAgICAgYXJncy5vdXRwdXRfdHN2LnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSkKICAgICAgICB0bXA9YXJncy5vdXRwdXRfdHN2LndpdGhfbmFtZSgnLicrYXJncy5vdXRwdXRfdHN2Lm5hbWUrJy5wYXJ0JykKICAgICAgICB3aXRoIHRtcC5vcGVuKCd3JyxuZXdsaW5lPScnKSBhcyBmaDoKICAgICAgICAgICAgd3I9Y3N2LkRpY3RXcml0ZXIoZmgsZmllbGRuYW1lcz1saXN0KHJvd3NbMF0ua2V5cygpKSxkZWxpbWl0ZXI9J1x0JykKICAgICAgICAgICAgd3Iud3JpdGVoZWFkZXIoKTsgd3Iud3JpdGVyb3dzKHJvd3MpCiAgICAgICAgdG1wLnJlcGxhY2UoYXJncy5vdXRwdXRfdHN2KQogICAgZWxzZToKICAgICAgICBpZiBhcmdzLnNlcXVlbmNlIGlzIE5vbmUgb3IgYXJncy5wcmlvcl9zdGFydCBpcyBOb25lIG9yIGFyZ3MucHJpb3JfZW5kIGlzIE5vbmU6CiAgICAgICAgICAgIGFwLmVycm9yKCdzaW5nbGUtY2FsbCBtb2RlIHJlcXVpcmVzIC0tc2VxdWVuY2UgLS1wcmlvci1zdGFydCAtLXByaW9yLWVuZCcpCiAgICAgICAgcHJpbnQoanNvbi5kdW1wcyhhc2RpY3QoY2FsbF9yZXBlYXQoYXJncy5zZXF1ZW5jZSxhcmdzLnByaW9yX3N0YXJ0LGFyZ3MucHJpb3JfZW5kLGFyZ3MuY2F0YWxvZ19tb3RpZikpLGluZGVudD0yKSkKCmlmIF9fbmFtZV9fPT0nX19tYWluX18nOiBjbGkoKQo=',
    Path(os.environ['SELFTEST_PATH']): 'IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwpmcm9tIF9fZnV0dXJlX18gaW1wb3J0IGFubm90YXRpb25zCmltcG9ydCBhcmdwYXJzZSwgY3N2LCBpbXBvcnRsaWIudXRpbCwganNvbiwgcmFuZG9tLCBzdGF0aXN0aWNzLCBzeXMKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgpETkE9J0FDR1QnCgpkZWYgbG9hZF9tb2R1bGUocGF0aDpQYXRoKToKICAgIHNwZWM9aW1wb3J0bGliLnV0aWwuc3BlY19mcm9tX2ZpbGVfbG9jYXRpb24oJ3JuYXRyX3JlZicscGF0aCkKICAgIG1vZD1pbXBvcnRsaWIudXRpbC5tb2R1bGVfZnJvbV9zcGVjKHNwZWMpOyBzeXMubW9kdWxlc1tzcGVjLm5hbWVdPW1vZDsgc3BlYy5sb2FkZXIuZXhlY19tb2R1bGUobW9kKTsgcmV0dXJuIG1vZAoKZGVmIGZsYW5rKHJuZyxuKTogcmV0dXJuICcnLmpvaW4ocm5nLmNob2ljZShETkEpIGZvciBfIGluIHJhbmdlKG4pKQoKZGVmIG11dGF0ZShzZXEscm5nLGVycm9yKToKICAgIGlmIGVycm9yPD0wOiByZXR1cm4gc2VxCiAgICBzdWI9ZXJyb3I7IGlucz1lcnJvci8zOyBkZWxlPWVycm9yLzM7IG91dD1bXQogICAgZm9yIGIgaW4gc2VxOgogICAgICAgIGlmIHJuZy5yYW5kb20oKTxkZWxlOiBjb250aW51ZQogICAgICAgIGlmIHJuZy5yYW5kb20oKTxzdWI6IG91dC5hcHBlbmQocm5nLmNob2ljZShbeCBmb3IgeCBpbiBETkEgaWYgeCE9Yl0pKQogICAgICAgIGVsc2U6IG91dC5hcHBlbmQoYikKICAgICAgICBpZiBybmcucmFuZG9tKCk8aW5zOiBvdXQuYXBwZW5kKHJuZy5jaG9pY2UoRE5BKSkKICAgIHJldHVybiAnJy5qb2luKG91dCkKCmRlZiBidWlsZF9jYXNlcygpOgogICAgY2FzZXM9W107IGlkeD0xCiAgICBkZWYgYWRkKG1vdGlmLHVuaXRzLGtpbmQ9J1BVUkUnLGVycm9yPTAuMCxjZW5zb3I9J05PTkUnLGludGVycnVwdD1Ob25lLGNvbXBvdW5kPU5vbmUpOgogICAgICAgIG5vbmxvY2FsIGlkeAogICAgICAgIHJuZz1yYW5kb20uUmFuZG9tKDIwMjYwODA3K2lkeCkKICAgICAgICBsZWZ0PWZsYW5rKHJuZyw2MCk7IHJpZ2h0PWZsYW5rKHJuZyw2MCkKICAgICAgICBpZiBraW5kPT0nUFVSRSc6IGJpb2xvZ2ljYWw9bW90aWYqdW5pdHM7IGJpb2xvZ2ljYWxfbHBzPWxlbihiaW9sb2dpY2FsKQogICAgICAgIGVsaWYga2luZD09J0lOVEVSUlVQVEVEJzoKICAgICAgICAgICAgdTEsaW50ZXIsdTI9aW50ZXJydXB0OyBiaW9sb2dpY2FsPW1vdGlmKnUxK2ludGVyK21vdGlmKnUyOyBiaW9sb2dpY2FsX2xwcz1tYXgodTEsdTIpKmxlbihtb3RpZikKICAgICAgICBlbGlmIGtpbmQ9PSdDT01QT1VORCc6CiAgICAgICAgICAgIGJpb2xvZ2ljYWw9Jycuam9pbihtKnUgZm9yIG0sdSBpbiBjb21wb3VuZCk7IGJpb2xvZ2ljYWxfbHBzPW1heChsZW4obSkqdSBmb3IgbSx1IGluIGNvbXBvdW5kKQogICAgICAgIGVsc2U6IHJhaXNlIFZhbHVlRXJyb3Ioa2luZCkKICAgICAgICBvYnNlcnZlZD1tdXRhdGUoYmlvbG9naWNhbCxybmcsZXJyb3IpCiAgICAgICAgbGVmdF9jPXJpZ2h0X2M9RmFsc2UKICAgICAgICBpZiBjZW5zb3I9PSdMRUZUJzoKICAgICAgICAgICAgbGVmdF9jPVRydWU7IG9ic2VydmVkPW9ic2VydmVkW21heCgxLGxlbihvYnNlcnZlZCkvLzQpOl07IGxlZnQ9JycKICAgICAgICBlbGlmIGNlbnNvcj09J1JJR0hUJzoKICAgICAgICAgICAgcmlnaHRfYz1UcnVlOyBvYnNlcnZlZD1vYnNlcnZlZFs6LW1heCgxLGxlbihvYnNlcnZlZCkvLzQpXTsgcmlnaHQ9JycKICAgICAgICBlbGlmIGNlbnNvcj09J0JPVEgnOgogICAgICAgICAgICBsZWZ0X2M9cmlnaHRfYz1UcnVlOyBrPW1heCgxLGxlbihvYnNlcnZlZCkvLzQpOyBvYnNlcnZlZD1vYnNlcnZlZFtrOi1rXTsgbGVmdD1yaWdodD0nJwogICAgICAgIHNlcT1sZWZ0K29ic2VydmVkK3JpZ2h0OyBwcz1sZW4obGVmdCk7IHBlPXBzK2xlbihvYnNlcnZlZCkKICAgICAgICBjYXNlcy5hcHBlbmQoZGljdChjYXNlX2lkPWYnU1lOe2lkeDowM2R9JyxraW5kPWtpbmQsY2F0YWxvZ19tb3RpZj1tb3RpZix0cnV0aF9jYW5vbmljYWxfbW90aWY9JycsdW5pdHM9dW5pdHMsCiAgICAgICAgICAgICAgICAgICAgICAgICAgZXJyb3JfcmF0ZT1lcnJvcixjZW5zb3I9Y2Vuc29yLGxlZnRfY2Vuc29yZWQ9c3RyKGxlZnRfYykubG93ZXIoKSxyaWdodF9jZW5zb3JlZD1zdHIocmlnaHRfYykubG93ZXIoKSwKICAgICAgICAgICAgICAgICAgICAgICAgICBiaW9sb2dpY2FsX3JlcGVhdF9icD1sZW4oYmlvbG9naWNhbCksYmlvbG9naWNhbF9scHNfYnA9YmlvbG9naWNhbF9scHMsb2JzZXJ2ZWRfdHJhY3RfYnA9bGVuKG9ic2VydmVkKSwKICAgICAgICAgICAgICAgICAgICAgICAgICBwcmlvcl9zdGFydD1wcyxwcmlvcl9lbmQ9cGUsc2VxdWVuY2U9c2VxKSkKICAgICAgICBpZHgrPTEKICAgIGZvciBtb3RpZix1bml0cyBpbiBbKCdBJyw1MCksKCdBQycsNDApLCgnQ0FHJywxMCksKCdDQUcnLDMwKSwoJ0NBRycsMTAwKSwoJ0FBR0dHJywzMCksKCdHR0dHQ0MnLDQwKSwoJ1RUVENBJywzMCksKCdBQ0dUR0NUQUFHVEMnLDEyKV06CiAgICAgICAgZm9yIGUgaW4gKDAuMCwwLjA1LDAuMTApOiBhZGQobW90aWYsdW5pdHMsZXJyb3I9ZSkKICAgIGFkZCgnQ0FHJyw0MCxraW5kPSdJTlRFUlJVUFRFRCcsZXJyb3I9MC4wNSxpbnRlcnJ1cHQ9KDIwLCdDQUEnLDIwKSkKICAgIGFkZCgnR0dHR0NDJywzMCxraW5kPSdJTlRFUlJVUFRFRCcsZXJyb3I9MC4wNSxpbnRlcnJ1cHQ9KDE1LCdBR0dHQ0MnLDE1KSkKICAgIGFkZCgnQ0FHJywwLGtpbmQ9J0NPTVBPVU5EJyxlcnJvcj0wLjA1LGNvbXBvdW5kPVsoJ0NBRycsMjApLCgnQ0FBJywxMCksKCdDQUcnLDIwKV0pCiAgICBhZGQoJ1RUVFRBJywwLGtpbmQ9J0NPTVBPVU5EJyxlcnJvcj0wLjA1LGNvbXBvdW5kPVsoJ1RUVFRBJywxNSksKCdUVFRDQScsMjApXSkKICAgIGZvciBjIGluICgnTEVGVCcsJ1JJR0hUJywnQk9USCcpOiBhZGQoJ0NBRycsMTAwLGVycm9yPTAuMDUsY2Vuc29yPWMpCiAgICByZXR1cm4gY2FzZXMKCmRlZiBtYWluKCk6CiAgICBhcD1hcmdwYXJzZS5Bcmd1bWVudFBhcnNlcigpOyBhcC5hZGRfYXJndW1lbnQoJy0tY2FsbGVyJyx0eXBlPVBhdGgscmVxdWlyZWQ9VHJ1ZSk7IGFwLmFkZF9hcmd1bWVudCgnLS1vdXRkaXInLHR5cGU9UGF0aCxyZXF1aXJlZD1UcnVlKQogICAgYXJncz1hcC5wYXJzZV9hcmdzKCk7IG1vZD1sb2FkX21vZHVsZShhcmdzLmNhbGxlcik7IGFyZ3Mub3V0ZGlyLm1rZGlyKHBhcmVudHM9VHJ1ZSxleGlzdF9vaz1UcnVlKQogICAgY2FzZXM9YnVpbGRfY2FzZXMoKQogICAgZm9yIGMgaW4gY2FzZXM6IGNbJ3RydXRoX2Nhbm9uaWNhbF9tb3RpZiddPW1vZC5jYW5vbmljYWxfbW90aWYoY1snY2F0YWxvZ19tb3RpZiddKQogICAgdHJ1dGg9YXJncy5vdXRkaXIvJ3N5bnRoZXRpY190cnV0aC50c3YnOyBpbnA9YXJncy5vdXRkaXIvJ3N5bnRoZXRpY19pbnB1dC50c3YnOyBmcT1hcmdzLm91dGRpci8nc3ludGhldGljX3JlYWRzLmZhc3RxJzsgY2FsbHM9YXJncy5vdXRkaXIvJ3N5bnRoZXRpY19yZWZlcmVuY2VfY2FsbHMudHN2JzsgcWM9YXJncy5vdXRkaXIvJ3N5bnRoZXRpY19yZWZlcmVuY2Vfc2VsZnRlc3QucWMudHN2JwogICAgZmllbGRzPWxpc3QoY2FzZXNbMF0ua2V5cygpKQogICAgd2l0aCB0cnV0aC5vcGVuKCd3JyxuZXdsaW5lPScnKSBhcyBmaDoKICAgICAgICB3cj1jc3YuRGljdFdyaXRlcihmaCxmaWVsZG5hbWVzPWZpZWxkcyxkZWxpbWl0ZXI9J1x0Jyk7IHdyLndyaXRlaGVhZGVyKCk7IHdyLndyaXRlcm93cyhjYXNlcykKICAgIHdpdGggaW5wLm9wZW4oJ3cnLG5ld2xpbmU9JycpIGFzIGZoOgogICAgICAgIGY9WydjYXNlX2lkJywnc2VxdWVuY2UnLCdwcmlvcl9zdGFydCcsJ3ByaW9yX2VuZCcsJ2NhdGFsb2dfbW90aWYnXTsgd3I9Y3N2LkRpY3RXcml0ZXIoZmgsZmllbGRuYW1lcz1mLGRlbGltaXRlcj0nXHQnKTsgd3Iud3JpdGVoZWFkZXIoKTsgd3Iud3JpdGVyb3dzKFt7azpjW2tdIGZvciBrIGluIGZ9IGZvciBjIGluIGNhc2VzXSkKICAgIHdpdGggZnEub3BlbigndycpIGFzIGZoOgogICAgICAgIGZvciBjIGluIGNhc2VzOgogICAgICAgICAgICBmaC53cml0ZShmIkB7Y1snY2FzZV9pZCddfSBraW5kPXtjWydraW5kJ119IGNlbnNvcj17Y1snY2Vuc29yJ119XG57Y1snc2VxdWVuY2UnXX1cbitcbnsnSScqbGVuKGNbJ3NlcXVlbmNlJ10pfVxuIikKICAgIG91dD1bXQogICAgZm9yIGMgaW4gY2FzZXM6CiAgICAgICAgY2FsbD1tb2QuY2FsbF9yZXBlYXQoY1snc2VxdWVuY2UnXSxpbnQoY1sncHJpb3Jfc3RhcnQnXSksaW50KGNbJ3ByaW9yX2VuZCddKSxbY1snY2F0YWxvZ19tb3RpZiddXSkKICAgICAgICBkPWNhbGwuX19kaWN0X18uY29weSgpOyBkWydjYXNlX2lkJ109Y1snY2FzZV9pZCddOyBkWyd0cnV0aF9jYW5vbmljYWxfbW90aWYnXT1jWyd0cnV0aF9jYW5vbmljYWxfbW90aWYnXTsgZFsndHJ1dGhfb2JzZXJ2ZWRfdHJhY3RfYnAnXT1jWydvYnNlcnZlZF90cmFjdF9icCddOyBkWydraW5kJ109Y1sna2luZCddOyBkWydlcnJvcl9yYXRlJ109Y1snZXJyb3JfcmF0ZSddOyBkWydjZW5zb3InXT1jWydjZW5zb3InXTsKICAgICAgICBkWydtb3RpZl9jb3JyZWN0J109c3RyKGRbJ2Nhbm9uaWNhbF9tb3RpZiddPT1jWyd0cnV0aF9jYW5vbmljYWxfbW90aWYnXSkubG93ZXIoKTsgZFsnbGVuZ3RoX2Fic19lcnJvcl9icCddPWFicyhpbnQoZFsncmVwZWF0X2JwX29ic2VydmVkJ10pLWludChjWydvYnNlcnZlZF90cmFjdF9icCddKSkKICAgICAgICBvdXQuYXBwZW5kKGQpCiAgICB3aXRoIGNhbGxzLm9wZW4oJ3cnLG5ld2xpbmU9JycpIGFzIGZoOgogICAgICAgIHdyPWNzdi5EaWN0V3JpdGVyKGZoLGZpZWxkbmFtZXM9bGlzdChvdXRbMF0ua2V5cygpKSxkZWxpbWl0ZXI9J1x0Jyk7IHdyLndyaXRlaGVhZGVyKCk7IHdyLndyaXRlcm93cyhvdXQpCiAgICBwdXJlPVtyIGZvciByIGluIG91dCBpZiByWydraW5kJ109PSdQVVJFJyBhbmQgclsnY2Vuc29yJ109PSdOT05FJ10KICAgIGVycm9ycz1zb3J0ZWQoclsnbGVuZ3RoX2Fic19lcnJvcl9icCddIGZvciByIGluIHB1cmUpCiAgICBwOTU9ZXJyb3JzW21pbihsZW4oZXJyb3JzKS0xLCBtYXgoMCwgaW50KDAuOTUqbGVuKGVycm9ycykpLTEpKV0KICAgIG1ldHJpY3M9WwogICAgICAgICgnZml4dHVyZV9jb3VudCcsbGVuKGNhc2VzKSksKCdwdXJlX3VuY2Vuc29yZWRfZml4dHVyZV9jb3VudCcsbGVuKHB1cmUpKSwKICAgICAgICAoJ2NhdGFsb2dfcHJpb3JfbW90aWZfYWNjdXJhY3knLHN1bShyWydtb3RpZl9jb3JyZWN0J109PSd0cnVlJyBmb3IgciBpbiBwdXJlKS9sZW4ocHVyZSkpLAogICAgICAgICgncHVyZV91bmNlbnNvcmVkX2xlbmd0aF9hYnNfZXJyb3JfbWVkaWFuX2JwJyxzdGF0aXN0aWNzLm1lZGlhbihlcnJvcnMpKSwKICAgICAgICAoJ3B1cmVfdW5jZW5zb3JlZF9sZW5ndGhfYWJzX2Vycm9yX3A5NV9icCcscDk1KSwKICAgICAgICAoJ2NvbnRyYWN0X3Njb3BlJywnUkVGRVJFTkNFX1NJTkdMRV9NT1RJRl9DT1JFX09OTFknKSwKICAgICAgICAoJ2NvbXBvdW5kX2xwc19zdGF0dXMnLCdOT1RfSU1QTEVNRU5URURfSU5fUkVGX1YwLjEuMCcpLAogICAgXQogICAgcGFzc2VkPShmbG9hdChtZXRyaWNzWzJdWzFdKT49MC45OSBhbmQgZmxvYXQobWV0cmljc1szXVsxXSk8PTUgYW5kIGZsb2F0KG1ldHJpY3NbNF1bMV0pPD0yMCkKICAgIG1ldHJpY3MuYXBwZW5kKCgnc2VsZnRlc3Rfc3RhdHVzJywnUEFTUycgaWYgcGFzc2VkIGVsc2UgJ1JFVklFVycpKQogICAgd2l0aCBxYy5vcGVuKCd3JyxuZXdsaW5lPScnKSBhcyBmaDoKICAgICAgICB3cj1jc3Yud3JpdGVyKGZoLGRlbGltaXRlcj0nXHQnKTsgd3Iud3JpdGVyb3coWydtZXRyaWMnLCd2YWx1ZSddKTsgd3Iud3JpdGVyb3dzKG1ldHJpY3MpCiAgICBwcmludChxYy5yZWFkX3RleHQoKSxlbmQ9JycpCiAgICBpZiBub3QgcGFzc2VkOiByYWlzZSBTeXN0ZW1FeGl0KDMpCgppZiBfX25hbWVfXz09J19fbWFpbl9fJzogbWFpbigpCg==',
}
for path,data in payloads.items():
    tmp=path.with_name('.'+path.name+'.part')
    tmp.write_bytes(base64.b64decode(data))
    tmp.chmod(0o755 if path.suffix=='.py' else 0o644)
    tmp.replace(path)
PYDECODE

python -m py_compile "$CALLER" "$SELFTEST"
python "$SELFTEST" --caller "$CALLER" --outdir "$BENCH"

gzip -t "$TARGET_EVIDENCE"
python - "$TARGET_EVIDENCE" "$BENCH/real_p01_regression_seed.tsv" <<'PYREAL'
import csv,gzip,sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2])
with gzip.open(src,'rt',encoding='utf-8',newline='') as fh:
    rd=csv.DictReader(fh,delimiter='\t')
    fields=rd.fieldnames or []
    required=['projection_id','read_id','representative_locus_id','canonical_motif','motif_length_bp','evidence_class','sizing_status','repeat_bp_estimate']
    miss=[x for x in required if x not in fields]
    if miss: raise SystemExit('ERROR: target evidence missing fields: '+','.join(miss))
    optional=[x for x in ['purity','confidence_label','best_mapq','target_source','region_type'] if x in fields]
    buckets={k:[] for k in ['1','2','3','4_6','7_10','11_20','gt20']}
    def bucket(v):
        try:n=int(float(v))
        except:return None
        if n==1:return '1'
        if n==2:return '2'
        if n==3:return '3'
        if n<=6:return '4_6'
        if n<=10:return '7_10'
        if n<=20:return '11_20'
        return 'gt20'
    for row in rd:
        if row.get('evidence_class')!='SPAN' or row.get('sizing_status')!='exact_span': continue
        b=bucket(row.get('motif_length_bp',''))
        if b and len(buckets[b])<10: buckets[b].append(row)
        if all(len(v)>=10 for v in buckets.values()): break
selected=[]
for b in ['1','2','3','4_6','7_10','11_20','gt20']:
    for row in buckets[b]:
        row=dict(row); row['motif_length_bin']=b; row['fixture_status']='SEED_MANIFEST_ONLY_RAW_SEQUENCE_MATERIALIZATION_PENDING'; selected.append(row)
if not selected: raise SystemExit('ERROR: no exact-span rows selected')
out_fields=['projection_id','read_id','representative_locus_id','canonical_motif','motif_length_bp','motif_length_bin','evidence_class','sizing_status','repeat_bp_estimate']+optional+['fixture_status']
tmp=out.with_name('.'+out.name+'.part')
with tmp.open('w',newline='',encoding='utf-8') as fh:
    wr=csv.DictWriter(fh,fieldnames=out_fields,delimiter='\t',extrasaction='ignore'); wr.writeheader(); wr.writerows(selected)
tmp.replace(out)
print(f'REAL_REGRESSION_SEED_PASS\trows={len(selected)}\t{out}')
PYREAL

CLI_BAK="$SSOT_CLI.pre_stage12a.$(date +%Y%m%d_%H%M%S).bak"
DB_BAK="$SSOT_DB.pre_stage12a.$(date +%Y%m%d_%H%M%S).bak"
cp -a "$SSOT_CLI" "$CLI_BAK"
cp -a "$SSOT_DB" "$DB_BAK"

python - "$SSOT_CLI" <<'PYSSOT'
from pathlib import Path
import sys,py_compile,hashlib
cli=Path(sys.argv[1]); text=cli.read_text(encoding='utf-8')
marker='# Stage 12A general caller bootstrap v0.1.0'
if marker in text:
    raise SystemExit('ERROR: Stage 12A SSOT patch marker already present')
import re
m=re.search(r'(?m)^TOOL_VERSION\s*=\s*["\']([^"\']+)["\']\s*$', text)
if not m:
    raise SystemExit('ERROR: SSOT TOOL_VERSION declaration not found')
print('SSOT_TOOL_VERSION_DETECTED\t'+m.group(1))
required_snippets=[
    'def add_decision(',
    'def add_interpretation(',
    'def add_contract(',
    'CREATE TABLE open_questions',
    'CREATE TABLE limitations',
]
missing=[x for x in required_snippets if x not in text]
if missing:
    raise SystemExit('ERROR: SSOT structural contract missing: '+', '.join(missing))
anchor='    current_metrics = [\n'
if text.count(anchor)!=1:
    raise SystemExit(f'ERROR: expected exactly one SSOT current_metrics anchor, observed {text.count(anchor)}')
insertion=r'''    # Stage 12A general caller bootstrap v0.1.0
    stage6am_qc = project_root / "qc/11_six_sample_frozen_p01_replay/ENCSR307SHM_pilot100k_mm2splice_v1/rnatr_six_sample_frozen_p01_replay_v0.1.5/six_sample_frozen_p01_replay.qc.tsv"
    stage6am_summary = project_root / "results/11_six_sample_frozen_p01_replay/ENCSR307SHM_pilot100k_mm2splice_v1/rnatr_six_sample_frozen_p01_replay_v0.1.5/six_sample_frozen_p01_replay.summary.tsv"
    stage6am_provenance = project_root / "results/11_six_sample_frozen_p01_replay/ENCSR307SHM_pilot100k_mm2splice_v1/rnatr_six_sample_frozen_p01_replay_v0.1.5/run_stage_provenance.tsv"
    general_contract = project_root / "docs/design/RNA_TR_Scout_general_repeat_caller_contract_v0.1.0.md"
    general_bench = project_root / "benchmarks/general_repeat_caller/v0.1.0"

    conn.execute("UPDATE open_questions SET status='CLOSED', blocking=0, next_action='Completed: six equalized 100k-read fetal-brain datasets replayed through the frozen P0/P1 pipeline; use as engineering validation only.', evidence_path=?, effective_at='2026-08-07T03:03:38+00:00' WHERE question_key='SIX_SAMPLE_REPLAY'", (str(stage6am_qc),))
    conn.execute("UPDATE open_questions SET status='CLOSED', blocking=0, next_action='Architecture contract frozen in v0.1.0; implementation remains a separate blocking task.', evidence_path=?, effective_at='2026-08-07T03:30:00+00:00' WHERE question_key='GENERAL_REPEAT_CALLER_CONTRACT'", (str(general_contract),))
    conn.execute("UPDATE open_questions SET status='OPEN', blocking=0, next_action='DEFER until the general caller is stable and fast enough to process many RNA long-read samples; do not estimate a precise locus/motif technical floor from the six-sample pilot.', evidence_path=?, effective_at='2026-08-07T03:30:00+00:00' WHERE question_key='RNA_TECHNICAL_FLOOR'", (str(stage6am_summary),))

    conn.execute('INSERT OR REPLACE INTO open_questions(question_key,question,priority,status,blocking,next_action,evidence_path,effective_at) VALUES(?,?,?,?,?,?,?,?)', ('GENERAL_REPEAT_CALLER_IMPLEMENTATION','Can the frozen general-caller contract be implemented for compound repeats, interruptions, RNA LPS, de-novo motif rescue, and censored molecules while preserving raw-read/locus-assignment semantics?','CRITICAL','OPEN',1,'Implement compound/interruption segmentation and LPS next, then materialize real P0/P1 raw-sequence regression fixtures and benchmark against the frozen pipeline.',str(general_contract),'2026-08-07T03:30:00+00:00'))
    conn.execute('INSERT OR REPLACE INTO open_questions(question_key,question,priority,status,blocking,next_action,evidence_path,effective_at) VALUES(?,?,?,?,?,?,?,?)', ('PERFORMANCE_OPTIMIZATION_11F_11H','How should production runtime be reduced, especially the computation corresponding to 11f/11h, and where can compiled CPU or GPU batching help?','HIGH','OPEN',0,'Profile after caller semantics stabilize; preserve the CPU/reference implementation as the correctness oracle.',str(stage6am_provenance),'2026-08-07T03:30:00+00:00'))
    conn.execute('INSERT OR REPLACE INTO limitations(limitation_key,statement,severity,status,mitigation,evidence_path,effective_at) VALUES(?,?,?,?,?,?,?)', ('SIX_SAMPLE_PANEL_ENGINEERING_ONLY','The six equalized fetal-brain 100k-read datasets are too small and biologically heterogeneous to define precise locus/motif/length/support-specific RNA technical distributions.','HIGH','ACTIVE','Use them only for engineering robustness and gross-artifact checks. Perform precise RNA background calibration only after the caller is stable/fast and many samples can be processed.',str(stage6am_summary),'2026-08-07T03:30:00+00:00'))
    conn.execute('INSERT OR REPLACE INTO limitations(limitation_key,statement,severity,status,mitigation,evidence_path,effective_at) VALUES(?,?,?,?,?,?,?)', ('CURRENT_RUNTIME_NOT_PRODUCTION_SCALE','The frozen P0/P1 implementation is too slow for routine full-depth cohorts; 11f and 11h are the primary observed hotspots.','HIGH','ACTIVE','Do not optimize prematurely. First stabilize general-caller semantics, then profile duplicate computation, Python overhead, compiled CPU, and GPU batching.',str(stage6am_provenance),'2026-08-07T03:30:00+00:00'))

    add_decision(conn,key='six_sample_scope_engineering_validation',category='development_scope',title='Six-sample panel is engineering validation only',statement='The six 100k-read fetal-brain comparison datasets close the replay/robustness gate but will not be used to estimate a precise RNA technical floor.',status='ACTIVE',confidence='HIGH',rationale='Six samples cannot separate technical variability, biological individual variability, expression/isoform differences, and sparse low-support loci with sufficient precision.',evidence_path=str(stage6am_summary),effective_at='2026-08-07T03:30:00+00:00')
    add_decision(conn,key='general_repeat_caller_contract_v0_1_0',category='algorithm_design',title='General repeat caller contract v0.1.0 frozen',statement='General repeat measurement will re-estimate raw-read repeat boundaries with an error-aware cyclic repeat model, treat catalog motifs as priors, preserve censored semantics, and explicitly support compound/interruption/LPS outputs.',status='ACTIVE',confidence='HIGH',rationale='This separates locus assignment from repeat measurement and provides a stable contract for implementation and benchmarking.',evidence_path=str(general_contract),effective_at='2026-08-07T03:30:00+00:00')
    add_interpretation(conn,key='stage6am_coarse_yield_sanity_only',fact='The target final P0/P1 evidence count and exact-span count fall within the six-sample replay ranges.',interpretation='No gross target-specific pipeline-yield failure is apparent at this coarse engineering level.',do_not='Do not interpret six-sample similarity as a locus-specific normal range, technical floor, pathogenicity result, or personal DNA genotype.',confidence='HIGH',evidence_path=str(stage6am_summary),evidence_metrics={'target_final_rows':49793,'panel_final_min':46160,'panel_final_max':53509,'target_exact_span':23867,'panel_exact_span_min':22114,'panel_exact_span_max':25886},status='ACTIVE',effective_at='2026-08-07T03:30:00+00:00')
    add_contract(conn,key='repeat_definition',name='Repeat definition and sizing',state='CONTRACT_FROZEN_REFERENCE_CORE_PROTOTYPE',statement='General-caller v0.1.0 contract freezes raw-read boundary re-estimation with cyclic error-aware motif alignment; catalog motifs are priors. The reference v0.1.0 single-motif core is implemented, while compound/interruption segmentation, LPS, censored interval inference, and production optimization remain pending.',implementation_id=None,evidence_path=str(general_contract))
    add_contract(conn,key='rna_lps',name='RNA longest pure segment',state='CONTRACT_FROZEN_NOT_IMPLEMENTED',statement='Final caller will keep exact-sequence LPS and error-aware inferred LPS distinct. Neither is complete in reference v0.1.0.',implementation_id=None,evidence_path=str(general_contract))
'''
text=text.replace(anchor,insertion+anchor,1)
tmp=cli.with_name('.'+cli.name+'.stage12a.part')
tmp.write_text(text,encoding='utf-8')
py_compile.compile(str(tmp),doraise=True)
tmp.replace(cli); cli.chmod(0o755)
print('SSOT_SOURCE_PATCH_PASS')
print('ssot_tool_version_preserved\t'+m.group(1))
print('ssot_cli_sha256\t'+hashlib.sha256(cli.read_bytes()).hexdigest())
PYSSOT

python "$SSOT_CLI" --project-root "$PROJECT_ROOT" rebuild
python "$SSOT_CLI" --project-root "$PROJECT_ROOT" validate
trap - ERR

SELF="$(readlink -f "$0")"
if [[ "$SELF" != "$SCRIPT_INSTALL" && ! -e "$SCRIPT_INSTALL" ]]; then
  cp "$SELF" "$SCRIPT_INSTALL.part"; chmod 0755 "$SCRIPT_INSTALL.part"; mv "$SCRIPT_INSTALL.part" "$SCRIPT_INSTALL"
fi

caller_sha="$(sha256sum "$CALLER" | awk '{print $1}')"
contract_sha="$(sha256sum "$CONTRACT" | awk '{print $1}')"
selftest_sha="$(sha256sum "$SELFTEST" | awk '{print $1}')"
synthetic_status="$(awk -F '\t' '$1=="selftest_status"{print $2}' "$BENCH/synthetic_reference_selftest.qc.tsv")"
real_seed_rows="$(($(wc -l < "$BENCH/real_p01_regression_seed.tsv")-1))"
{
  printf 'metric\tvalue\n'
  printf 'stage_version\t%s\n' "$STAGE_VERSION"
  printf 'stage6am_scope\tENGINEERING_VALIDATION_ONLY\n'
  printf 'general_caller_contract\tFROZEN_V0.1.0\n'
  printf 'reference_core\tSINGLE_MOTIF_CYCLIC_ERROR_AWARE_PROTOTYPE\n'
  printf 'synthetic_selftest_status\t%s\n' "$synthetic_status"
  printf 'real_regression_seed_rows\t%s\n' "$real_seed_rows"
  printf 'real_regression_seed_status\tSEED_MANIFEST_ONLY_RAW_SEQUENCE_MATERIALIZATION_PENDING\n'
  printf 'compound_interruption_lps\tNOT_IMPLEMENTED_NEXT\n'
  printf 'rna_technical_floor\tDEFERRED_UNTIL_LARGE_COHORT_AFTER_CALLER_STABILIZATION\n'
  printf 'performance_optimization\tDEFERRED_UNTIL_CALLER_SEMANTICS_STABLE\n'
  printf 'caller_sha256\t%s\n' "$caller_sha"
  printf 'contract_sha256\t%s\n' "$contract_sha"
  printf 'selftest_sha256\t%s\n' "$selftest_sha"
  printf 'next_gate\tIMPLEMENT_COMPOUND_INTERRUPTION_LPS_AND_MATERIALIZE_REAL_REGRESSION_READS\n'
  printf 'audit_status\tPASS\n'
} > "$QC.part"
mv "$QC.part" "$QC"

echo '===== STAGE 12A COMPLETE ====='
cat "$BENCH/synthetic_reference_selftest.qc.tsv"
echo
echo '===== BOOTSTRAP QC ====='
cat "$QC"
echo
echo "Contract: $CONTRACT"
echo "Caller:   $CALLER"
echo "Bench:    $BENCH"
echo "QC:       $QC"
echo 'STAGE12A_PASS'
